### ISSUE TITLE
Best practice for getting more compute for VSCode?

### ISSUE THREAD

**Issue by bretttully** [aws-samples/amazon-sagemaker-codeserver#1]
Hi team -- very cool, but it's not clear how we can throw more compute at Option A? Pylance struggles on the default approach for Option A with a decent sized git repo, and I haven't tried turning on Copilot yet. Is Option B the recommended way around this?

**Comment by giuseppeporcelli** [comment]
Hi @bretttully. Thanks for reaching out. Indeed, if you need more compute for a better experience with the libraries you are used to work with, option B in the blog is going to give you a broad choice of compute options. We plan to include additional guidance in the documentation based on your valuable feedback. Thanks.
