### ISSUE TITLE
will be python plot shown as can be done by usning X11

### ISSUE THREAD

**Issue by Sandy4321** [aws-samples/amazon-sagemaker-codeserver#23]
will be python plot shown
as can be done by usning X11

for example
import matplotlib.pyplot as plt

# generate data
x = [1, 2, 3, 4, 5]
y = [2, 4, 6, 8, 10]

# plot data
plt.plot(x, y)
plt.title('Simple Plot')
plt.xlabel('X Axis')
plt.ylabel('Y Axis')

# show plot
plt.show()

**Comment by giuseppeporcelli** [comment]
Hi, I believe this feature request is more appropriate for the code-server project:
https://github.com/coder/code-server

Thanks!
