### ISSUE TITLE
Doesn't work for al2-v1 sagemaker-notebook?

### ISSUE THREAD

**Issue by zhh210** [aws-samples/amazon-sagemaker-codeserver#29]
The script works on an `al2-v2` sagemaker notebook instance. However, the `code-server launcher` button never shows up for `al2-v1` instance regardless putting it in lifecycle configuration or manually install it.

**Comment by giuseppeporcelli** [comment]
Thanks for reporting this issue. Could you share the console outputs from the install procedure?

**Comment by giuseppeporcelli** [comment]
JupyterLab extension support for `al2-v1` has been deprecated in release 0.2.0. As a consequence, the JupyterLab launcher button will not appear. However, you can still access code-server by typing the direct address in the browser (see the Caveats / know limitations section in the README).
