### ISSUE TITLE
Installation fails on JS1

### ISSUE THREAD

**Issue by orangewise** [aws-samples/amazon-sagemaker-codeserver#3]
I'm trying out this solution but get the following error during install in Studio (JL1):

```
[LabBuildApp] Building jupyterlab assets (build:prod:minimize)
[LabBuildApp] > node /opt/conda/lib/python3.7/site-packages/jupyterlab/staging/yarn.js install --non-interactive
[LabBuildApp] yarn install v1.15.2
[1/5] Validating package.json...
[2/5] Resolving packages...
warning @amzn/aws-hil-axis-jupyter-lab-extension > react-scripts > babel-eslint@10.0.3: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
error Couldn't find package "@amzn/sagemaker-ui-log-event@^3.30.0" required by "@amzn/aws-hil-axis-jupyter-lab-extension@file:../extensions/amzn-aws-hil-axis-jupyter-lab-extension-0.0.7.tgz" on the "npm" registry.
```

**Comment by giuseppeporcelli** [comment]
Hi @orangewise, thanks for raising this issue.
Could you please provide the steps to reproduce this issue? I have just run the install procedure on Studio-JL1 with no error.

Some other useful info that would help troubleshooting are:

1. JupyterLab version (Help menu > About JupyterLab)
2. SageMaker Studio version (you can get it by running `jupyter labextension list` on the terminal, and checking the version of the @amzn/sagemaker-ui extension
3. If you installed manually or with lifecycle configs
4. If it is a fresh Studio user-profile or pre-existing
5. If it is a fresh Studio JupyterServer app or pre-existing

**Comment by orangewise** [comment]
Good afternoon @giuseppeporcelli, 

the installation failed because I thought we were running JL3 which was incorrect. The installation works without issues now.

Thanks!
