### ISSUE TITLE
Sagemaker Notebook Instance in VPC, code-server --install-extension hangs

### ISSUE THREAD

**Issue by nicornk** [aws-samples/amazon-sagemaker-codeserver#6]
I am running a notebook instance in a VPC with egress controls.

The command `code-server --install-extension ms-python.python --force` of the `install-codeserver.sh` file hangs on step:

```
Installing extensions...
```

Do you know which URL the `code-server`process is reaching out to, to download the extension?

**Comment by giuseppeporcelli** [comment]
code-server uses the [Open VSX](https://open-vsx.org/) gallery to offer extensions. Please check [this section](https://coder.com/docs/code-server/latest/FAQ#why-cant-code-server-use-microsofts-extension-marketplace) in the documentation for further information.

Based on my experiments, the URLs to allowlist are:
https://open-vsx.org/
https://openvsxorg.blob.core.windows.net/

Alternatively, you can pre-download the extension _vsix_ file, and install from it as described [here](https://coder.com/docs/code-server/latest/FAQ#how-do-i-install-an-extension).

**Comment by nicornk** [comment]
Allowlisting `https://open-vsx.org/` did the trick. Thanks
